//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from antlr4/OCL.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class OCLParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, T__40=41, T__41=42, T__42=43, T__43=44, T__44=45, 
		T__45=46, T__46=47, T__47=48, T__48=49, T__49=50, T__50=51, T__51=52, 
		T__52=53, T__53=54, T__54=55, T__55=56, T__56=57, T__57=58, T__58=59, 
		T__59=60, T__60=61, T__61=62, T__62=63, T__63=64, T__64=65, T__65=66, 
		T__66=67, T__67=68, T__68=69, T__69=70, T__70=71, T__71=72, T__72=73, 
		T__73=74, T__74=75, T__75=76, T__76=77, T__77=78, T__78=79, T__79=80, 
		T__80=81, T__81=82, T__82=83, T__83=84, T__84=85, T__85=86, T__86=87, 
		T__87=88, T__88=89, T__89=90, T__90=91, T__91=92, T__92=93, T__93=94, 
		T__94=95, T__95=96, T__96=97, T__97=98, T__98=99, T__99=100, T__100=101, 
		T__101=102, T__102=103, T__103=104, T__104=105, T__105=106, T__106=107, 
		T__107=108, T__108=109, T__109=110, T__110=111, T__111=112, T__112=113, 
		T__113=114, BOOLEAN_LITERAL=115, FLOAT_LITERAL=116, STRING1_LITERAL=117, 
		STRING2_LITERAL=118, ENUMERATION_LITERAL=119, NULL_LITERAL=120, MULTILINE_COMMENT=121, 
		LINE_COMMENT=122, NEWLINE=123, INT=124, ID=125, WS=126;
	public const int
		RULE_type = 0, RULE_expressionList = 1, RULE_expression = 2, RULE_conditionalExpression = 3, 
		RULE_letExpression = 4, RULE_letBinding = 5, RULE_basicExpression = 6, 
		RULE_logicalExpression = 7, RULE_equalityExpression = 8, RULE_additiveExpression = 9, 
		RULE_multiplicativeExpression = 10, RULE_unaryExpression = 11, RULE_navigationExpression = 12, 
		RULE_primaryFactor = 13, RULE_postfixSuffix = 14, RULE_identOptType = 15, 
		RULE_identOptTypeList = 16, RULE_setExpression = 17, RULE_identifier = 18, 
		RULE_qualified_name = 19;
	public static readonly string[] ruleNames = {
		"type", "expressionList", "expression", "conditionalExpression", "letExpression", 
		"letBinding", "basicExpression", "logicalExpression", "equalityExpression", 
		"additiveExpression", "multiplicativeExpression", "unaryExpression", "navigationExpression", 
		"primaryFactor", "postfixSuffix", "identOptType", "identOptTypeList", 
		"setExpression", "identifier", "qualified_name"
	};

	private static readonly string[] _LiteralNames = {
		null, "'Sequence'", "'('", "')'", "'Set'", "'Bag'", "'OrderedSet'", "'Ref'", 
		"'Map'", "','", "'Function'", "'if'", "'then'", "'else'", "'endif'", "'let'", 
		"'in'", "':'", "'='", "'.'", "'['", "']'", "'and'", "'&'", "'or'", "'xor'", 
		"'=>'", "'implies'", "'<'", "'>'", "'>='", "'<='", "'/='", "'<>'", "'/:'", 
		"'<:'", "'+'", "'-'", "'..'", "'|->'", "'*'", "'/'", "'mod'", "'div'", 
		"'not'", "'?'", "'!'", "'allInstances'", "'oclType'", "'oclIsUndefined'", 
		"'oclIsInvalid'", "'oclIsNew'", "'oclAsSet'", "'oclIsTypeOf'", "'oclIsKindOf'", 
		"'oclIsType'", "'oclAsType'", "'size'", "'max'", "'min'", "'indexOf'", 
		"'at'", "'isUnique'", "'->'", "'isEmpty'", "'notEmpty'", "'asSet'", "'asBag'", 
		"'asOrderedSet'", "'asSequence'", "'any'", "'first'", "'last'", "'reverse'", 
		"'floor'", "'round'", "'abs'", "'sum'", "'characters'", "'toInteger'", 
		"'toReal'", "'toBoolean'", "'toUpperCase'", "'toLowerCase'", "'union'", 
		"'intersection'", "'includes'", "'excludes'", "'including'", "'excluding'", 
		"'includesAll'", "'symmetricDifference'", "'excludesAll'", "'prepend'", 
		"'append'", "'count'", "'equalsIgnoreCase'", "'collect'", "'|'", "'select'", 
		"'reject'", "'forAll'", "'exists'", "'one'", "'closure'", "'sortedBy'", 
		"'insertAt'", "'iterate'", "';'", "'OrderedSet{'", "'}'", "'Bag{'", "'Set{'", 
		"'Sequence{'", "'Map{'", null, null, null, null, null, "'null'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, "BOOLEAN_LITERAL", "FLOAT_LITERAL", 
		"STRING1_LITERAL", "STRING2_LITERAL", "ENUMERATION_LITERAL", "NULL_LITERAL", 
		"MULTILINE_COMMENT", "LINE_COMMENT", "NEWLINE", "INT", "ID", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "OCL.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static OCLParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public OCLParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public OCLParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class TypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext[] type() {
			return GetRuleContexts<TypeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type(int i) {
			return GetRuleContext<TypeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 0, RULE_type);
		try {
			State = 80;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				EnterOuterAlt(_localctx, 1);
				{
				State = 40;
				Match(T__0);
				State = 41;
				Match(T__1);
				State = 42;
				type();
				State = 43;
				Match(T__2);
				}
				break;
			case T__3:
				EnterOuterAlt(_localctx, 2);
				{
				State = 45;
				Match(T__3);
				State = 46;
				Match(T__1);
				State = 47;
				type();
				State = 48;
				Match(T__2);
				}
				break;
			case T__4:
				EnterOuterAlt(_localctx, 3);
				{
				State = 50;
				Match(T__4);
				State = 51;
				Match(T__1);
				State = 52;
				type();
				State = 53;
				Match(T__2);
				}
				break;
			case T__5:
				EnterOuterAlt(_localctx, 4);
				{
				State = 55;
				Match(T__5);
				State = 56;
				Match(T__1);
				State = 57;
				type();
				State = 58;
				Match(T__2);
				}
				break;
			case T__6:
				EnterOuterAlt(_localctx, 5);
				{
				State = 60;
				Match(T__6);
				State = 61;
				Match(T__1);
				State = 62;
				type();
				State = 63;
				Match(T__2);
				}
				break;
			case T__7:
				EnterOuterAlt(_localctx, 6);
				{
				State = 65;
				Match(T__7);
				State = 66;
				Match(T__1);
				State = 67;
				type();
				State = 68;
				Match(T__8);
				State = 69;
				type();
				State = 70;
				Match(T__2);
				}
				break;
			case T__9:
				EnterOuterAlt(_localctx, 7);
				{
				State = 72;
				Match(T__9);
				State = 73;
				Match(T__1);
				State = 74;
				type();
				State = 75;
				Match(T__8);
				State = 76;
				type();
				State = 77;
				Match(T__2);
				}
				break;
			case ID:
				EnterOuterAlt(_localctx, 8);
				{
				State = 79;
				identifier();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ExpressionListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expressionList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterExpressionList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitExpressionList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionListContext expressionList() {
		ExpressionListContext _localctx = new ExpressionListContext(Context, State);
		EnterRule(_localctx, 2, RULE_expressionList);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 87;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 82;
					expression();
					State = 83;
					Match(T__8);
					}
					} 
				}
				State = 89;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			}
			State = 90;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LogicalExpressionContext logicalExpression() {
			return GetRuleContext<LogicalExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConditionalExpressionContext conditionalExpression() {
			return GetRuleContext<ConditionalExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LetExpressionContext letExpression() {
			return GetRuleContext<LetExpressionContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 4, RULE_expression);
		try {
			State = 95;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__1:
			case T__35:
			case T__36:
			case T__43:
			case T__44:
			case T__45:
			case T__108:
			case T__110:
			case T__111:
			case T__112:
			case T__113:
			case BOOLEAN_LITERAL:
			case FLOAT_LITERAL:
			case STRING1_LITERAL:
			case STRING2_LITERAL:
			case ENUMERATION_LITERAL:
			case NULL_LITERAL:
			case INT:
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 92;
				logicalExpression();
				}
				break;
			case T__10:
				EnterOuterAlt(_localctx, 2);
				{
				State = 93;
				conditionalExpression();
				}
				break;
			case T__14:
				EnterOuterAlt(_localctx, 3);
				{
				State = 94;
				letExpression();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionalExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ConditionalExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_conditionalExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterConditionalExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitConditionalExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConditionalExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionalExpressionContext conditionalExpression() {
		ConditionalExpressionContext _localctx = new ConditionalExpressionContext(Context, State);
		EnterRule(_localctx, 6, RULE_conditionalExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97;
			Match(T__10);
			State = 98;
			expression();
			State = 99;
			Match(T__11);
			State = 100;
			expression();
			State = 101;
			Match(T__12);
			State = 102;
			expression();
			State = 103;
			Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LetExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LetBindingContext[] letBinding() {
			return GetRuleContexts<LetBindingContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LetBindingContext letBinding(int i) {
			return GetRuleContext<LetBindingContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public LetExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_letExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterLetExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitLetExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLetExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LetExpressionContext letExpression() {
		LetExpressionContext _localctx = new LetExpressionContext(Context, State);
		EnterRule(_localctx, 8, RULE_letExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			Match(T__14);
			State = 106;
			letBinding();
			State = 111;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__8) {
				{
				{
				State = 107;
				Match(T__8);
				State = 108;
				letBinding();
				}
				}
				State = 113;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 114;
			Match(T__15);
			State = 115;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LetBindingContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(OCLParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public LetBindingContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_letBinding; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterLetBinding(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitLetBinding(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLetBinding(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LetBindingContext letBinding() {
		LetBindingContext _localctx = new LetBindingContext(Context, State);
		EnterRule(_localctx, 10, RULE_letBinding);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 117;
			Match(ID);
			State = 120;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__16) {
				{
				State = 118;
				Match(T__16);
				State = 119;
				type();
				}
			}

			State = 122;
			Match(T__17);
			State = 123;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BasicExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL_LITERAL() { return GetToken(OCLParser.NULL_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN_LITERAL() { return GetToken(OCLParser.BOOLEAN_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(OCLParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_LITERAL() { return GetToken(OCLParser.FLOAT_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING1_LITERAL() { return GetToken(OCLParser.STRING1_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING2_LITERAL() { return GetToken(OCLParser.STRING2_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENUMERATION_LITERAL() { return GetToken(OCLParser.ENUMERATION_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(OCLParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BasicExpressionContext basicExpression() {
			return GetRuleContext<BasicExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionListContext expressionList() {
			return GetRuleContext<ExpressionListContext>(0);
		}
		public BasicExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_basicExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterBasicExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitBasicExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBasicExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BasicExpressionContext basicExpression() {
		return basicExpression(0);
	}

	private BasicExpressionContext basicExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		BasicExpressionContext _localctx = new BasicExpressionContext(Context, _parentState);
		BasicExpressionContext _prevctx = _localctx;
		int _startState = 12;
		EnterRecursionRule(_localctx, 12, RULE_basicExpression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 138;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case NULL_LITERAL:
				{
				State = 126;
				Match(NULL_LITERAL);
				}
				break;
			case BOOLEAN_LITERAL:
				{
				State = 127;
				Match(BOOLEAN_LITERAL);
				}
				break;
			case INT:
				{
				State = 128;
				Match(INT);
				}
				break;
			case FLOAT_LITERAL:
				{
				State = 129;
				Match(FLOAT_LITERAL);
				}
				break;
			case STRING1_LITERAL:
				{
				State = 130;
				Match(STRING1_LITERAL);
				}
				break;
			case STRING2_LITERAL:
				{
				State = 131;
				Match(STRING2_LITERAL);
				}
				break;
			case ENUMERATION_LITERAL:
				{
				State = 132;
				Match(ENUMERATION_LITERAL);
				}
				break;
			case ID:
				{
				State = 133;
				Match(ID);
				}
				break;
			case T__1:
				{
				State = 134;
				Match(T__1);
				State = 135;
				expression();
				State = 136;
				Match(T__2);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 156;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 154;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,7,Context) ) {
					case 1:
						{
						_localctx = new BasicExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_basicExpression);
						State = 140;
						if (!(Precpred(Context, 10))) throw new FailedPredicateException(this, "Precpred(Context, 10)");
						State = 141;
						Match(T__18);
						State = 142;
						Match(ID);
						}
						break;
					case 2:
						{
						_localctx = new BasicExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_basicExpression);
						State = 143;
						if (!(Precpred(Context, 9))) throw new FailedPredicateException(this, "Precpred(Context, 9)");
						State = 144;
						Match(T__1);
						State = 146;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 123351460775940L) != 0) || ((((_la - 109)) & ~0x3f) == 0 && ((1L << (_la - 109)) & 102397L) != 0)) {
							{
							State = 145;
							expressionList();
							}
						}

						State = 148;
						Match(T__2);
						}
						break;
					case 3:
						{
						_localctx = new BasicExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_basicExpression);
						State = 149;
						if (!(Precpred(Context, 8))) throw new FailedPredicateException(this, "Precpred(Context, 8)");
						State = 150;
						Match(T__19);
						State = 151;
						expression();
						State = 152;
						Match(T__20);
						}
						break;
					}
					} 
				}
				State = 158;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class LogicalExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public EqualityExpressionContext[] equalityExpression() {
			return GetRuleContexts<EqualityExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public EqualityExpressionContext equalityExpression(int i) {
			return GetRuleContext<EqualityExpressionContext>(i);
		}
		public LogicalExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterLogicalExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitLogicalExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicalExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicalExpressionContext logicalExpression() {
		LogicalExpressionContext _localctx = new LogicalExpressionContext(Context, State);
		EnterRule(_localctx, 14, RULE_logicalExpression);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 159;
			equalityExpression();
			State = 164;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 160;
					_la = TokenStream.LA(1);
					if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 264241152L) != 0)) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					State = 161;
					equalityExpression();
					}
					} 
				}
				State = 166;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,9,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EqualityExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public AdditiveExpressionContext[] additiveExpression() {
			return GetRuleContexts<AdditiveExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public AdditiveExpressionContext additiveExpression(int i) {
			return GetRuleContext<AdditiveExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LetExpressionContext letExpression() {
			return GetRuleContext<LetExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConditionalExpressionContext conditionalExpression() {
			return GetRuleContext<ConditionalExpressionContext>(0);
		}
		public EqualityExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_equalityExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterEqualityExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitEqualityExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEqualityExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EqualityExpressionContext equalityExpression() {
		EqualityExpressionContext _localctx = new EqualityExpressionContext(Context, State);
		EnterRule(_localctx, 16, RULE_equalityExpression);
		int _la;
		try {
			State = 181;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,12,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 167;
				additiveExpression();
				State = 168;
				Match(T__17);
				State = 171;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__14:
					{
					State = 169;
					letExpression();
					}
					break;
				case T__10:
					{
					State = 170;
					conditionalExpression();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 173;
				additiveExpression();
				State = 178;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 68451434496L) != 0)) {
					{
					{
					State = 174;
					_la = TokenStream.LA(1);
					if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 68451434496L) != 0)) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					State = 175;
					additiveExpression();
					}
					}
					State = 180;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AdditiveExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MultiplicativeExpressionContext[] multiplicativeExpression() {
			return GetRuleContexts<MultiplicativeExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public MultiplicativeExpressionContext multiplicativeExpression(int i) {
			return GetRuleContext<MultiplicativeExpressionContext>(i);
		}
		public AdditiveExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_additiveExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterAdditiveExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitAdditiveExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAdditiveExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AdditiveExpressionContext additiveExpression() {
		AdditiveExpressionContext _localctx = new AdditiveExpressionContext(Context, State);
		EnterRule(_localctx, 18, RULE_additiveExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 183;
			multiplicativeExpression();
			State = 188;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 1030792151040L) != 0)) {
				{
				{
				State = 184;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 1030792151040L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 185;
				multiplicativeExpression();
				}
				}
				State = 190;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MultiplicativeExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public UnaryExpressionContext[] unaryExpression() {
			return GetRuleContexts<UnaryExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public UnaryExpressionContext unaryExpression(int i) {
			return GetRuleContext<UnaryExpressionContext>(i);
		}
		public MultiplicativeExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_multiplicativeExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterMultiplicativeExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitMultiplicativeExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiplicativeExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MultiplicativeExpressionContext multiplicativeExpression() {
		MultiplicativeExpressionContext _localctx = new MultiplicativeExpressionContext(Context, State);
		EnterRule(_localctx, 20, RULE_multiplicativeExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 191;
			unaryExpression();
			State = 196;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 16492674416640L) != 0)) {
				{
				{
				State = 192;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 16492674416640L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 193;
				unaryExpression();
				}
				}
				State = 198;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class UnaryExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public UnaryExpressionContext unaryExpression() {
			return GetRuleContext<UnaryExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NavigationExpressionContext navigationExpression() {
			return GetRuleContext<NavigationExpressionContext>(0);
		}
		public UnaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unaryExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterUnaryExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitUnaryExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnaryExpressionContext unaryExpression() {
		UnaryExpressionContext _localctx = new UnaryExpressionContext(Context, State);
		EnterRule(_localctx, 22, RULE_unaryExpression);
		int _la;
		try {
			State = 202;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__35:
			case T__36:
			case T__43:
			case T__44:
			case T__45:
				EnterOuterAlt(_localctx, 1);
				{
				State = 199;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 123351460741120L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 200;
				unaryExpression();
				}
				break;
			case T__1:
			case T__108:
			case T__110:
			case T__111:
			case T__112:
			case T__113:
			case BOOLEAN_LITERAL:
			case FLOAT_LITERAL:
			case STRING1_LITERAL:
			case STRING2_LITERAL:
			case ENUMERATION_LITERAL:
			case NULL_LITERAL:
			case INT:
			case ID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 201;
				navigationExpression();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NavigationExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PrimaryFactorContext primaryFactor() {
			return GetRuleContext<PrimaryFactorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public PostfixSuffixContext[] postfixSuffix() {
			return GetRuleContexts<PostfixSuffixContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PostfixSuffixContext postfixSuffix(int i) {
			return GetRuleContext<PostfixSuffixContext>(i);
		}
		public NavigationExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_navigationExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterNavigationExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitNavigationExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNavigationExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NavigationExpressionContext navigationExpression() {
		NavigationExpressionContext _localctx = new NavigationExpressionContext(Context, State);
		EnterRule(_localctx, 24, RULE_navigationExpression);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 204;
			primaryFactor();
			State = 208;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__18 || _la==T__62) {
				{
				{
				State = 205;
				postfixSuffix();
				}
				}
				State = 210;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrimaryFactorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SetExpressionContext setExpression() {
			return GetRuleContext<SetExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BasicExpressionContext basicExpression() {
			return GetRuleContext<BasicExpressionContext>(0);
		}
		public PrimaryFactorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_primaryFactor; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterPrimaryFactor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitPrimaryFactor(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrimaryFactor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrimaryFactorContext primaryFactor() {
		PrimaryFactorContext _localctx = new PrimaryFactorContext(Context, State);
		EnterRule(_localctx, 26, RULE_primaryFactor);
		try {
			State = 213;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__108:
			case T__110:
			case T__111:
			case T__112:
			case T__113:
				EnterOuterAlt(_localctx, 1);
				{
				State = 211;
				setExpression();
				}
				break;
			case T__1:
			case BOOLEAN_LITERAL:
			case FLOAT_LITERAL:
			case STRING1_LITERAL:
			case STRING2_LITERAL:
			case ENUMERATION_LITERAL:
			case NULL_LITERAL:
			case INT:
			case ID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 212;
				basicExpression(0);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PostfixSuffixContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(OCLParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(OCLParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentOptTypeContext identOptType() {
			return GetRuleContext<IdentOptTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentOptTypeListContext identOptTypeList() {
			return GetRuleContext<IdentOptTypeListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		public PostfixSuffixContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_postfixSuffix; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterPostfixSuffix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitPostfixSuffix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPostfixSuffix(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PostfixSuffixContext postfixSuffix() {
		PostfixSuffixContext _localctx = new PostfixSuffixContext(Context, State);
		EnterRule(_localctx, 28, RULE_postfixSuffix);
		int _la;
		try {
			State = 613;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,41,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 215;
				Match(T__18);
				State = 216;
				Match(T__46);
				State = 217;
				Match(T__1);
				State = 218;
				Match(T__2);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 219;
				Match(T__18);
				State = 220;
				Match(T__47);
				State = 221;
				Match(T__1);
				State = 222;
				Match(T__2);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 223;
				Match(T__18);
				State = 224;
				Match(T__48);
				State = 225;
				Match(T__1);
				State = 226;
				Match(T__2);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 227;
				Match(T__18);
				State = 228;
				Match(T__49);
				State = 229;
				Match(T__1);
				State = 230;
				Match(T__2);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 231;
				Match(T__18);
				State = 232;
				Match(T__50);
				State = 233;
				Match(T__1);
				State = 234;
				Match(T__2);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 235;
				Match(T__18);
				State = 236;
				Match(T__51);
				State = 237;
				Match(T__1);
				State = 238;
				Match(T__2);
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 239;
				Match(T__18);
				State = 240;
				Match(T__52);
				State = 241;
				Match(T__1);
				State = 242;
				expression();
				State = 243;
				Match(T__2);
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 245;
				Match(T__18);
				State = 246;
				Match(T__53);
				State = 247;
				Match(T__1);
				State = 248;
				expression();
				State = 249;
				Match(T__2);
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 251;
				Match(T__18);
				State = 252;
				Match(T__54);
				State = 253;
				Match(T__1);
				State = 254;
				expression();
				State = 255;
				Match(T__2);
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 257;
				Match(T__18);
				State = 258;
				Match(T__55);
				State = 259;
				Match(T__1);
				State = 260;
				expression();
				State = 261;
				Match(T__2);
				State = 264;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
				case 1:
					{
					State = 262;
					Match(T__18);
					State = 263;
					Match(ID);
					}
					break;
				}
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 266;
				Match(T__18);
				State = 267;
				Match(T__56);
				State = 268;
				Match(T__1);
				State = 269;
				Match(T__2);
				}
				break;
			case 12:
				EnterOuterAlt(_localctx, 12);
				{
				State = 270;
				Match(T__18);
				State = 271;
				Match(T__57);
				State = 272;
				Match(T__1);
				State = 273;
				Match(T__2);
				}
				break;
			case 13:
				EnterOuterAlt(_localctx, 13);
				{
				State = 274;
				Match(T__18);
				State = 275;
				Match(T__58);
				State = 276;
				Match(T__1);
				State = 277;
				Match(T__2);
				}
				break;
			case 14:
				EnterOuterAlt(_localctx, 14);
				{
				State = 278;
				Match(T__18);
				State = 279;
				Match(T__59);
				State = 280;
				Match(T__1);
				State = 281;
				expression();
				State = 282;
				Match(T__2);
				}
				break;
			case 15:
				EnterOuterAlt(_localctx, 15);
				{
				State = 284;
				Match(T__18);
				State = 285;
				Match(T__60);
				State = 286;
				Match(T__1);
				State = 287;
				expression();
				State = 288;
				Match(T__2);
				State = 291;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
				case 1:
					{
					State = 289;
					Match(T__18);
					State = 290;
					Match(ID);
					}
					break;
				}
				}
				break;
			case 16:
				EnterOuterAlt(_localctx, 16);
				{
				State = 293;
				Match(T__18);
				State = 294;
				Match(T__61);
				}
				break;
			case 17:
				EnterOuterAlt(_localctx, 17);
				{
				State = 295;
				Match(T__18);
				State = 296;
				Match(ID);
				State = 297;
				Match(T__1);
				State = 306;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 123351460775940L) != 0) || ((((_la - 109)) & ~0x3f) == 0 && ((1L << (_la - 109)) & 102397L) != 0)) {
					{
					State = 298;
					expression();
					State = 303;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__8) {
						{
						{
						State = 299;
						Match(T__8);
						State = 300;
						expression();
						}
						}
						State = 305;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 308;
				Match(T__2);
				State = 311;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
				case 1:
					{
					State = 309;
					Match(T__18);
					State = 310;
					Match(ID);
					}
					break;
				}
				}
				break;
			case 18:
				EnterOuterAlt(_localctx, 18);
				{
				State = 313;
				Match(T__18);
				State = 314;
				Match(ID);
				}
				break;
			case 19:
				EnterOuterAlt(_localctx, 19);
				{
				State = 315;
				Match(T__62);
				State = 316;
				Match(T__56);
				State = 317;
				Match(T__1);
				State = 318;
				Match(T__2);
				}
				break;
			case 20:
				EnterOuterAlt(_localctx, 20);
				{
				State = 319;
				Match(T__62);
				State = 320;
				Match(T__63);
				State = 321;
				Match(T__1);
				State = 322;
				Match(T__2);
				}
				break;
			case 21:
				EnterOuterAlt(_localctx, 21);
				{
				State = 323;
				Match(T__62);
				State = 324;
				Match(T__64);
				State = 325;
				Match(T__1);
				State = 326;
				Match(T__2);
				}
				break;
			case 22:
				EnterOuterAlt(_localctx, 22);
				{
				State = 327;
				Match(T__62);
				State = 328;
				Match(T__65);
				State = 329;
				Match(T__1);
				State = 330;
				Match(T__2);
				}
				break;
			case 23:
				EnterOuterAlt(_localctx, 23);
				{
				State = 331;
				Match(T__62);
				State = 332;
				Match(T__66);
				State = 333;
				Match(T__1);
				State = 334;
				Match(T__2);
				}
				break;
			case 24:
				EnterOuterAlt(_localctx, 24);
				{
				State = 335;
				Match(T__62);
				State = 336;
				Match(T__67);
				State = 337;
				Match(T__1);
				State = 338;
				Match(T__2);
				}
				break;
			case 25:
				EnterOuterAlt(_localctx, 25);
				{
				State = 339;
				Match(T__62);
				State = 340;
				Match(T__68);
				State = 341;
				Match(T__1);
				State = 342;
				Match(T__2);
				}
				break;
			case 26:
				EnterOuterAlt(_localctx, 26);
				{
				State = 343;
				Match(T__62);
				State = 344;
				Match(T__69);
				State = 345;
				Match(T__1);
				State = 346;
				Match(T__2);
				State = 349;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,23,Context) ) {
				case 1:
					{
					State = 347;
					Match(T__18);
					State = 348;
					Match(ID);
					}
					break;
				}
				}
				break;
			case 27:
				EnterOuterAlt(_localctx, 27);
				{
				State = 351;
				Match(T__62);
				State = 352;
				Match(T__70);
				State = 353;
				Match(T__1);
				State = 354;
				Match(T__2);
				State = 357;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
				case 1:
					{
					State = 355;
					Match(T__18);
					State = 356;
					Match(ID);
					}
					break;
				}
				}
				break;
			case 28:
				EnterOuterAlt(_localctx, 28);
				{
				State = 359;
				Match(T__62);
				State = 360;
				Match(T__71);
				State = 361;
				Match(T__1);
				State = 362;
				Match(T__2);
				State = 365;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
				case 1:
					{
					State = 363;
					Match(T__18);
					State = 364;
					Match(ID);
					}
					break;
				}
				}
				break;
			case 29:
				EnterOuterAlt(_localctx, 29);
				{
				State = 367;
				Match(T__62);
				State = 368;
				Match(T__72);
				State = 369;
				Match(T__1);
				State = 370;
				Match(T__2);
				}
				break;
			case 30:
				EnterOuterAlt(_localctx, 30);
				{
				State = 371;
				Match(T__62);
				State = 372;
				Match(T__73);
				State = 373;
				Match(T__1);
				State = 374;
				Match(T__2);
				}
				break;
			case 31:
				EnterOuterAlt(_localctx, 31);
				{
				State = 375;
				Match(T__62);
				State = 376;
				Match(T__74);
				State = 377;
				Match(T__1);
				State = 378;
				Match(T__2);
				}
				break;
			case 32:
				EnterOuterAlt(_localctx, 32);
				{
				State = 379;
				Match(T__62);
				State = 380;
				Match(T__75);
				State = 381;
				Match(T__1);
				State = 382;
				Match(T__2);
				}
				break;
			case 33:
				EnterOuterAlt(_localctx, 33);
				{
				State = 383;
				Match(T__62);
				State = 384;
				Match(T__47);
				State = 385;
				Match(T__1);
				State = 386;
				Match(T__2);
				}
				break;
			case 34:
				EnterOuterAlt(_localctx, 34);
				{
				State = 387;
				Match(T__62);
				State = 388;
				Match(T__48);
				State = 389;
				Match(T__1);
				State = 390;
				Match(T__2);
				}
				break;
			case 35:
				EnterOuterAlt(_localctx, 35);
				{
				State = 391;
				Match(T__62);
				State = 392;
				Match(T__49);
				State = 393;
				Match(T__1);
				State = 394;
				Match(T__2);
				}
				break;
			case 36:
				EnterOuterAlt(_localctx, 36);
				{
				State = 395;
				Match(T__62);
				State = 396;
				Match(T__50);
				State = 397;
				Match(T__1);
				State = 398;
				Match(T__2);
				}
				break;
			case 37:
				EnterOuterAlt(_localctx, 37);
				{
				State = 399;
				Match(T__62);
				State = 400;
				Match(T__76);
				State = 401;
				Match(T__1);
				State = 402;
				Match(T__2);
				}
				break;
			case 38:
				EnterOuterAlt(_localctx, 38);
				{
				State = 403;
				Match(T__62);
				State = 404;
				Match(T__57);
				State = 405;
				Match(T__1);
				State = 406;
				Match(T__2);
				}
				break;
			case 39:
				EnterOuterAlt(_localctx, 39);
				{
				State = 407;
				Match(T__62);
				State = 408;
				Match(T__58);
				State = 409;
				Match(T__1);
				State = 410;
				Match(T__2);
				}
				break;
			case 40:
				EnterOuterAlt(_localctx, 40);
				{
				State = 411;
				Match(T__62);
				State = 412;
				Match(T__77);
				State = 413;
				Match(T__1);
				State = 414;
				Match(T__2);
				}
				break;
			case 41:
				EnterOuterAlt(_localctx, 41);
				{
				State = 415;
				Match(T__62);
				State = 416;
				Match(T__78);
				State = 417;
				Match(T__1);
				State = 418;
				Match(T__2);
				}
				break;
			case 42:
				EnterOuterAlt(_localctx, 42);
				{
				State = 419;
				Match(T__62);
				State = 420;
				Match(T__79);
				State = 421;
				Match(T__1);
				State = 422;
				Match(T__2);
				}
				break;
			case 43:
				EnterOuterAlt(_localctx, 43);
				{
				State = 423;
				Match(T__62);
				State = 424;
				Match(T__80);
				State = 425;
				Match(T__1);
				State = 426;
				Match(T__2);
				}
				break;
			case 44:
				EnterOuterAlt(_localctx, 44);
				{
				State = 427;
				Match(T__62);
				State = 428;
				Match(T__81);
				State = 429;
				Match(T__1);
				State = 430;
				Match(T__2);
				}
				break;
			case 45:
				EnterOuterAlt(_localctx, 45);
				{
				State = 431;
				Match(T__62);
				State = 432;
				Match(T__82);
				State = 433;
				Match(T__1);
				State = 434;
				Match(T__2);
				}
				break;
			case 46:
				EnterOuterAlt(_localctx, 46);
				{
				State = 435;
				Match(T__62);
				State = 436;
				_la = TokenStream.LA(1);
				if ( !(((((_la - 60)) & ~0x3f) == 0 && ((1L << (_la - 60)) & 68702699521L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 437;
				Match(T__1);
				State = 438;
				expression();
				State = 439;
				Match(T__2);
				}
				break;
			case 47:
				EnterOuterAlt(_localctx, 47);
				{
				State = 441;
				Match(T__62);
				State = 442;
				Match(T__95);
				State = 443;
				Match(T__1);
				State = 444;
				expression();
				State = 445;
				Match(T__2);
				}
				break;
			case 48:
				EnterOuterAlt(_localctx, 48);
				{
				State = 447;
				Match(T__62);
				State = 448;
				_la = TokenStream.LA(1);
				if ( !(_la==T__55 || _la==T__60) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 449;
				Match(T__1);
				State = 450;
				expression();
				State = 451;
				Match(T__2);
				State = 454;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,26,Context) ) {
				case 1:
					{
					State = 452;
					Match(T__18);
					State = 453;
					Match(ID);
					}
					break;
				}
				}
				break;
			case 49:
				EnterOuterAlt(_localctx, 49);
				{
				State = 456;
				Match(T__62);
				State = 457;
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 31525197391593472L) != 0)) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 458;
				Match(T__1);
				State = 459;
				expression();
				State = 460;
				Match(T__2);
				}
				break;
			case 50:
				EnterOuterAlt(_localctx, 50);
				{
				State = 462;
				Match(T__62);
				State = 463;
				Match(T__96);
				State = 464;
				Match(T__1);
				State = 468;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,27,Context) ) {
				case 1:
					{
					State = 465;
					identOptType();
					State = 466;
					Match(T__97);
					}
					break;
				}
				State = 470;
				expression();
				State = 471;
				Match(T__2);
				}
				break;
			case 51:
				EnterOuterAlt(_localctx, 51);
				{
				State = 473;
				Match(T__62);
				State = 474;
				Match(T__98);
				State = 475;
				Match(T__1);
				State = 479;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,28,Context) ) {
				case 1:
					{
					State = 476;
					identOptType();
					State = 477;
					Match(T__97);
					}
					break;
				}
				State = 481;
				expression();
				State = 482;
				Match(T__2);
				}
				break;
			case 52:
				EnterOuterAlt(_localctx, 52);
				{
				State = 484;
				Match(T__62);
				State = 485;
				Match(T__99);
				State = 486;
				Match(T__1);
				State = 490;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,29,Context) ) {
				case 1:
					{
					State = 487;
					identOptType();
					State = 488;
					Match(T__97);
					}
					break;
				}
				State = 492;
				expression();
				State = 493;
				Match(T__2);
				}
				break;
			case 53:
				EnterOuterAlt(_localctx, 53);
				{
				State = 495;
				Match(T__62);
				State = 496;
				Match(T__100);
				State = 497;
				Match(T__1);
				State = 501;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,30,Context) ) {
				case 1:
					{
					State = 498;
					identOptTypeList();
					State = 499;
					Match(T__97);
					}
					break;
				}
				State = 503;
				expression();
				State = 504;
				Match(T__2);
				}
				break;
			case 54:
				EnterOuterAlt(_localctx, 54);
				{
				State = 506;
				Match(T__62);
				State = 507;
				Match(T__101);
				State = 508;
				Match(T__1);
				State = 512;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,31,Context) ) {
				case 1:
					{
					State = 509;
					identOptTypeList();
					State = 510;
					Match(T__97);
					}
					break;
				}
				State = 514;
				expression();
				State = 515;
				Match(T__2);
				}
				break;
			case 55:
				EnterOuterAlt(_localctx, 55);
				{
				State = 517;
				Match(T__62);
				State = 518;
				Match(T__102);
				State = 519;
				Match(T__1);
				State = 523;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,32,Context) ) {
				case 1:
					{
					State = 520;
					identOptType();
					State = 521;
					Match(T__97);
					}
					break;
				}
				State = 525;
				expression();
				State = 526;
				Match(T__2);
				}
				break;
			case 56:
				EnterOuterAlt(_localctx, 56);
				{
				State = 528;
				Match(T__62);
				State = 529;
				Match(T__69);
				State = 530;
				Match(T__1);
				State = 534;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,33,Context) ) {
				case 1:
					{
					State = 531;
					identOptType();
					State = 532;
					Match(T__97);
					}
					break;
				}
				State = 536;
				expression();
				State = 537;
				Match(T__2);
				State = 540;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,34,Context) ) {
				case 1:
					{
					State = 538;
					Match(T__18);
					State = 539;
					Match(ID);
					}
					break;
				}
				}
				break;
			case 57:
				EnterOuterAlt(_localctx, 57);
				{
				State = 542;
				Match(T__62);
				State = 543;
				Match(T__103);
				State = 544;
				Match(T__1);
				State = 548;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,35,Context) ) {
				case 1:
					{
					State = 545;
					identOptType();
					State = 546;
					Match(T__97);
					}
					break;
				}
				State = 550;
				expression();
				State = 551;
				Match(T__2);
				}
				break;
			case 58:
				EnterOuterAlt(_localctx, 58);
				{
				State = 553;
				Match(T__62);
				State = 554;
				Match(T__104);
				State = 555;
				Match(T__1);
				State = 559;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,36,Context) ) {
				case 1:
					{
					State = 556;
					identOptType();
					State = 557;
					Match(T__97);
					}
					break;
				}
				State = 561;
				expression();
				State = 562;
				Match(T__2);
				}
				break;
			case 59:
				EnterOuterAlt(_localctx, 59);
				{
				State = 564;
				Match(T__62);
				State = 565;
				Match(T__61);
				State = 566;
				Match(T__1);
				State = 570;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,37,Context) ) {
				case 1:
					{
					State = 567;
					identOptType();
					State = 568;
					Match(T__97);
					}
					break;
				}
				State = 572;
				expression();
				State = 573;
				Match(T__2);
				}
				break;
			case 60:
				EnterOuterAlt(_localctx, 60);
				{
				State = 575;
				Match(T__62);
				State = 576;
				Match(T__105);
				State = 577;
				Match(T__1);
				State = 578;
				expression();
				State = 579;
				Match(T__8);
				State = 580;
				expression();
				State = 581;
				Match(T__2);
				}
				break;
			case 61:
				EnterOuterAlt(_localctx, 61);
				{
				State = 583;
				Match(T__62);
				State = 584;
				Match(T__106);
				State = 585;
				Match(T__1);
				State = 586;
				identifier();
				State = 587;
				Match(T__107);
				State = 588;
				identOptType();
				State = 589;
				Match(T__17);
				State = 590;
				expression();
				State = 591;
				Match(T__97);
				State = 592;
				expression();
				State = 593;
				Match(T__2);
				}
				break;
			case 62:
				EnterOuterAlt(_localctx, 62);
				{
				State = 595;
				Match(T__62);
				State = 596;
				Match(ID);
				State = 597;
				Match(T__1);
				State = 606;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 123351460775940L) != 0) || ((((_la - 109)) & ~0x3f) == 0 && ((1L << (_la - 109)) & 102397L) != 0)) {
					{
					State = 598;
					expression();
					State = 603;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==T__8) {
						{
						{
						State = 599;
						Match(T__8);
						State = 600;
						expression();
						}
						}
						State = 605;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 608;
				Match(T__2);
				State = 611;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,40,Context) ) {
				case 1:
					{
					State = 609;
					Match(T__18);
					State = 610;
					Match(ID);
					}
					break;
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentOptTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(OCLParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public IdentOptTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identOptType; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterIdentOptType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitIdentOptType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentOptType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdentOptTypeContext identOptType() {
		IdentOptTypeContext _localctx = new IdentOptTypeContext(Context, State);
		EnterRule(_localctx, 30, RULE_identOptType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 615;
			Match(ID);
			State = 618;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__16) {
				{
				State = 616;
				Match(T__16);
				State = 617;
				type();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentOptTypeListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentOptTypeContext[] identOptType() {
			return GetRuleContexts<IdentOptTypeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentOptTypeContext identOptType(int i) {
			return GetRuleContext<IdentOptTypeContext>(i);
		}
		public IdentOptTypeListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identOptTypeList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterIdentOptTypeList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitIdentOptTypeList(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentOptTypeList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdentOptTypeListContext identOptTypeList() {
		IdentOptTypeListContext _localctx = new IdentOptTypeListContext(Context, State);
		EnterRule(_localctx, 32, RULE_identOptTypeList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 620;
			identOptType();
			State = 625;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__8) {
				{
				{
				State = 621;
				Match(T__8);
				State = 622;
				identOptType();
				}
				}
				State = 627;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SetExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionListContext expressionList() {
			return GetRuleContext<ExpressionListContext>(0);
		}
		public SetExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_setExpression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterSetExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitSetExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSetExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SetExpressionContext setExpression() {
		SetExpressionContext _localctx = new SetExpressionContext(Context, State);
		EnterRule(_localctx, 34, RULE_setExpression);
		int _la;
		try {
			State = 653;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__108:
				EnterOuterAlt(_localctx, 1);
				{
				State = 628;
				Match(T__108);
				State = 630;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 123351460775940L) != 0) || ((((_la - 109)) & ~0x3f) == 0 && ((1L << (_la - 109)) & 102397L) != 0)) {
					{
					State = 629;
					expressionList();
					}
				}

				State = 632;
				Match(T__109);
				}
				break;
			case T__110:
				EnterOuterAlt(_localctx, 2);
				{
				State = 633;
				Match(T__110);
				State = 635;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 123351460775940L) != 0) || ((((_la - 109)) & ~0x3f) == 0 && ((1L << (_la - 109)) & 102397L) != 0)) {
					{
					State = 634;
					expressionList();
					}
				}

				State = 637;
				Match(T__109);
				}
				break;
			case T__111:
				EnterOuterAlt(_localctx, 3);
				{
				State = 638;
				Match(T__111);
				State = 640;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 123351460775940L) != 0) || ((((_la - 109)) & ~0x3f) == 0 && ((1L << (_la - 109)) & 102397L) != 0)) {
					{
					State = 639;
					expressionList();
					}
				}

				State = 642;
				Match(T__109);
				}
				break;
			case T__112:
				EnterOuterAlt(_localctx, 4);
				{
				State = 643;
				Match(T__112);
				State = 645;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 123351460775940L) != 0) || ((((_la - 109)) & ~0x3f) == 0 && ((1L << (_la - 109)) & 102397L) != 0)) {
					{
					State = 644;
					expressionList();
					}
				}

				State = 647;
				Match(T__109);
				}
				break;
			case T__113:
				EnterOuterAlt(_localctx, 5);
				{
				State = 648;
				Match(T__113);
				State = 650;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 123351460775940L) != 0) || ((((_la - 109)) & ~0x3f) == 0 && ((1L << (_la - 109)) & 102397L) != 0)) {
					{
					State = 649;
					expressionList();
					}
				}

				State = 652;
				Match(T__109);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(OCLParser.ID, 0); }
		public IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdentifierContext identifier() {
		IdentifierContext _localctx = new IdentifierContext(Context, State);
		EnterRule(_localctx, 36, RULE_identifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 655;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Qualified_nameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ENUMERATION_LITERAL() { return GetToken(OCLParser.ENUMERATION_LITERAL, 0); }
		public Qualified_nameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_qualified_name; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.EnterQualified_name(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IOCLListener typedListener = listener as IOCLListener;
			if (typedListener != null) typedListener.ExitQualified_name(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IOCLVisitor<TResult> typedVisitor = visitor as IOCLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQualified_name(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Qualified_nameContext qualified_name() {
		Qualified_nameContext _localctx = new Qualified_nameContext(Context, State);
		EnterRule(_localctx, 38, RULE_qualified_name);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 657;
			Match(ENUMERATION_LITERAL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 6: return basicExpression_sempred((BasicExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool basicExpression_sempred(BasicExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 10);
		case 1: return Precpred(Context, 9);
		case 2: return Precpred(Context, 8);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,126,660,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,
		7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,1,0,1,0,1,0,1,0,1,0,
		1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,
		0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,
		3,0,81,8,0,1,1,1,1,1,1,5,1,86,8,1,10,1,12,1,89,9,1,1,1,1,1,1,2,1,2,1,2,
		3,2,96,8,2,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,4,1,4,1,4,1,4,5,4,110,8,4,
		10,4,12,4,113,9,4,1,4,1,4,1,4,1,5,1,5,1,5,3,5,121,8,5,1,5,1,5,1,5,1,6,
		1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,3,6,139,8,6,1,6,1,6,1,
		6,1,6,1,6,1,6,3,6,147,8,6,1,6,1,6,1,6,1,6,1,6,1,6,5,6,155,8,6,10,6,12,
		6,158,9,6,1,7,1,7,1,7,5,7,163,8,7,10,7,12,7,166,9,7,1,8,1,8,1,8,1,8,3,
		8,172,8,8,1,8,1,8,1,8,5,8,177,8,8,10,8,12,8,180,9,8,3,8,182,8,8,1,9,1,
		9,1,9,5,9,187,8,9,10,9,12,9,190,9,9,1,10,1,10,1,10,5,10,195,8,10,10,10,
		12,10,198,9,10,1,11,1,11,1,11,3,11,203,8,11,1,12,1,12,5,12,207,8,12,10,
		12,12,12,210,9,12,1,13,1,13,3,13,214,8,13,1,14,1,14,1,14,1,14,1,14,1,14,
		1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,
		1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,
		1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,
		1,14,3,14,265,8,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,3,14,292,8,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,5,14,302,8,14,
		10,14,12,14,305,9,14,3,14,307,8,14,1,14,1,14,1,14,3,14,312,8,14,1,14,1,
		14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,1,14,1,14,1,14,1,14,1,14,1,14,3,14,350,8,14,1,14,1,14,1,14,1,14,1,14,
		1,14,3,14,358,8,14,1,14,1,14,1,14,1,14,1,14,1,14,3,14,366,8,14,1,14,1,
		14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,1,14,3,14,455,8,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,
		1,14,1,14,3,14,469,8,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,3,
		14,480,8,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,3,14,491,8,14,
		1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,3,14,502,8,14,1,14,1,14,1,
		14,1,14,1,14,1,14,1,14,1,14,1,14,3,14,513,8,14,1,14,1,14,1,14,1,14,1,14,
		1,14,1,14,1,14,1,14,3,14,524,8,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,1,14,3,14,535,8,14,1,14,1,14,1,14,1,14,3,14,541,8,14,1,14,1,14,1,14,
		1,14,1,14,1,14,3,14,549,8,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,
		14,3,14,560,8,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,3,14,571,
		8,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,
		1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,1,14,
		1,14,1,14,5,14,602,8,14,10,14,12,14,605,9,14,3,14,607,8,14,1,14,1,14,1,
		14,3,14,612,8,14,3,14,614,8,14,1,15,1,15,1,15,3,15,619,8,15,1,16,1,16,
		1,16,5,16,624,8,16,10,16,12,16,627,9,16,1,17,1,17,3,17,631,8,17,1,17,1,
		17,1,17,3,17,636,8,17,1,17,1,17,1,17,3,17,641,8,17,1,17,1,17,1,17,3,17,
		646,8,17,1,17,1,17,1,17,3,17,651,8,17,1,17,3,17,654,8,17,1,18,1,18,1,19,
		1,19,1,19,0,1,12,20,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,
		38,0,8,1,0,22,27,2,0,17,18,28,35,1,0,36,39,1,0,40,43,2,0,36,37,44,46,2,
		0,60,60,84,95,2,0,56,56,61,61,1,0,52,54,767,0,80,1,0,0,0,2,87,1,0,0,0,
		4,95,1,0,0,0,6,97,1,0,0,0,8,105,1,0,0,0,10,117,1,0,0,0,12,138,1,0,0,0,
		14,159,1,0,0,0,16,181,1,0,0,0,18,183,1,0,0,0,20,191,1,0,0,0,22,202,1,0,
		0,0,24,204,1,0,0,0,26,213,1,0,0,0,28,613,1,0,0,0,30,615,1,0,0,0,32,620,
		1,0,0,0,34,653,1,0,0,0,36,655,1,0,0,0,38,657,1,0,0,0,40,41,5,1,0,0,41,
		42,5,2,0,0,42,43,3,0,0,0,43,44,5,3,0,0,44,81,1,0,0,0,45,46,5,4,0,0,46,
		47,5,2,0,0,47,48,3,0,0,0,48,49,5,3,0,0,49,81,1,0,0,0,50,51,5,5,0,0,51,
		52,5,2,0,0,52,53,3,0,0,0,53,54,5,3,0,0,54,81,1,0,0,0,55,56,5,6,0,0,56,
		57,5,2,0,0,57,58,3,0,0,0,58,59,5,3,0,0,59,81,1,0,0,0,60,61,5,7,0,0,61,
		62,5,2,0,0,62,63,3,0,0,0,63,64,5,3,0,0,64,81,1,0,0,0,65,66,5,8,0,0,66,
		67,5,2,0,0,67,68,3,0,0,0,68,69,5,9,0,0,69,70,3,0,0,0,70,71,5,3,0,0,71,
		81,1,0,0,0,72,73,5,10,0,0,73,74,5,2,0,0,74,75,3,0,0,0,75,76,5,9,0,0,76,
		77,3,0,0,0,77,78,5,3,0,0,78,81,1,0,0,0,79,81,3,36,18,0,80,40,1,0,0,0,80,
		45,1,0,0,0,80,50,1,0,0,0,80,55,1,0,0,0,80,60,1,0,0,0,80,65,1,0,0,0,80,
		72,1,0,0,0,80,79,1,0,0,0,81,1,1,0,0,0,82,83,3,4,2,0,83,84,5,9,0,0,84,86,
		1,0,0,0,85,82,1,0,0,0,86,89,1,0,0,0,87,85,1,0,0,0,87,88,1,0,0,0,88,90,
		1,0,0,0,89,87,1,0,0,0,90,91,3,4,2,0,91,3,1,0,0,0,92,96,3,14,7,0,93,96,
		3,6,3,0,94,96,3,8,4,0,95,92,1,0,0,0,95,93,1,0,0,0,95,94,1,0,0,0,96,5,1,
		0,0,0,97,98,5,11,0,0,98,99,3,4,2,0,99,100,5,12,0,0,100,101,3,4,2,0,101,
		102,5,13,0,0,102,103,3,4,2,0,103,104,5,14,0,0,104,7,1,0,0,0,105,106,5,
		15,0,0,106,111,3,10,5,0,107,108,5,9,0,0,108,110,3,10,5,0,109,107,1,0,0,
		0,110,113,1,0,0,0,111,109,1,0,0,0,111,112,1,0,0,0,112,114,1,0,0,0,113,
		111,1,0,0,0,114,115,5,16,0,0,115,116,3,4,2,0,116,9,1,0,0,0,117,120,5,125,
		0,0,118,119,5,17,0,0,119,121,3,0,0,0,120,118,1,0,0,0,120,121,1,0,0,0,121,
		122,1,0,0,0,122,123,5,18,0,0,123,124,3,4,2,0,124,11,1,0,0,0,125,126,6,
		6,-1,0,126,139,5,120,0,0,127,139,5,115,0,0,128,139,5,124,0,0,129,139,5,
		116,0,0,130,139,5,117,0,0,131,139,5,118,0,0,132,139,5,119,0,0,133,139,
		5,125,0,0,134,135,5,2,0,0,135,136,3,4,2,0,136,137,5,3,0,0,137,139,1,0,
		0,0,138,125,1,0,0,0,138,127,1,0,0,0,138,128,1,0,0,0,138,129,1,0,0,0,138,
		130,1,0,0,0,138,131,1,0,0,0,138,132,1,0,0,0,138,133,1,0,0,0,138,134,1,
		0,0,0,139,156,1,0,0,0,140,141,10,10,0,0,141,142,5,19,0,0,142,155,5,125,
		0,0,143,144,10,9,0,0,144,146,5,2,0,0,145,147,3,2,1,0,146,145,1,0,0,0,146,
		147,1,0,0,0,147,148,1,0,0,0,148,155,5,3,0,0,149,150,10,8,0,0,150,151,5,
		20,0,0,151,152,3,4,2,0,152,153,5,21,0,0,153,155,1,0,0,0,154,140,1,0,0,
		0,154,143,1,0,0,0,154,149,1,0,0,0,155,158,1,0,0,0,156,154,1,0,0,0,156,
		157,1,0,0,0,157,13,1,0,0,0,158,156,1,0,0,0,159,164,3,16,8,0,160,161,7,
		0,0,0,161,163,3,16,8,0,162,160,1,0,0,0,163,166,1,0,0,0,164,162,1,0,0,0,
		164,165,1,0,0,0,165,15,1,0,0,0,166,164,1,0,0,0,167,168,3,18,9,0,168,171,
		5,18,0,0,169,172,3,8,4,0,170,172,3,6,3,0,171,169,1,0,0,0,171,170,1,0,0,
		0,172,182,1,0,0,0,173,178,3,18,9,0,174,175,7,1,0,0,175,177,3,18,9,0,176,
		174,1,0,0,0,177,180,1,0,0,0,178,176,1,0,0,0,178,179,1,0,0,0,179,182,1,
		0,0,0,180,178,1,0,0,0,181,167,1,0,0,0,181,173,1,0,0,0,182,17,1,0,0,0,183,
		188,3,20,10,0,184,185,7,2,0,0,185,187,3,20,10,0,186,184,1,0,0,0,187,190,
		1,0,0,0,188,186,1,0,0,0,188,189,1,0,0,0,189,19,1,0,0,0,190,188,1,0,0,0,
		191,196,3,22,11,0,192,193,7,3,0,0,193,195,3,22,11,0,194,192,1,0,0,0,195,
		198,1,0,0,0,196,194,1,0,0,0,196,197,1,0,0,0,197,21,1,0,0,0,198,196,1,0,
		0,0,199,200,7,4,0,0,200,203,3,22,11,0,201,203,3,24,12,0,202,199,1,0,0,
		0,202,201,1,0,0,0,203,23,1,0,0,0,204,208,3,26,13,0,205,207,3,28,14,0,206,
		205,1,0,0,0,207,210,1,0,0,0,208,206,1,0,0,0,208,209,1,0,0,0,209,25,1,0,
		0,0,210,208,1,0,0,0,211,214,3,34,17,0,212,214,3,12,6,0,213,211,1,0,0,0,
		213,212,1,0,0,0,214,27,1,0,0,0,215,216,5,19,0,0,216,217,5,47,0,0,217,218,
		5,2,0,0,218,614,5,3,0,0,219,220,5,19,0,0,220,221,5,48,0,0,221,222,5,2,
		0,0,222,614,5,3,0,0,223,224,5,19,0,0,224,225,5,49,0,0,225,226,5,2,0,0,
		226,614,5,3,0,0,227,228,5,19,0,0,228,229,5,50,0,0,229,230,5,2,0,0,230,
		614,5,3,0,0,231,232,5,19,0,0,232,233,5,51,0,0,233,234,5,2,0,0,234,614,
		5,3,0,0,235,236,5,19,0,0,236,237,5,52,0,0,237,238,5,2,0,0,238,614,5,3,
		0,0,239,240,5,19,0,0,240,241,5,53,0,0,241,242,5,2,0,0,242,243,3,4,2,0,
		243,244,5,3,0,0,244,614,1,0,0,0,245,246,5,19,0,0,246,247,5,54,0,0,247,
		248,5,2,0,0,248,249,3,4,2,0,249,250,5,3,0,0,250,614,1,0,0,0,251,252,5,
		19,0,0,252,253,5,55,0,0,253,254,5,2,0,0,254,255,3,4,2,0,255,256,5,3,0,
		0,256,614,1,0,0,0,257,258,5,19,0,0,258,259,5,56,0,0,259,260,5,2,0,0,260,
		261,3,4,2,0,261,264,5,3,0,0,262,263,5,19,0,0,263,265,5,125,0,0,264,262,
		1,0,0,0,264,265,1,0,0,0,265,614,1,0,0,0,266,267,5,19,0,0,267,268,5,57,
		0,0,268,269,5,2,0,0,269,614,5,3,0,0,270,271,5,19,0,0,271,272,5,58,0,0,
		272,273,5,2,0,0,273,614,5,3,0,0,274,275,5,19,0,0,275,276,5,59,0,0,276,
		277,5,2,0,0,277,614,5,3,0,0,278,279,5,19,0,0,279,280,5,60,0,0,280,281,
		5,2,0,0,281,282,3,4,2,0,282,283,5,3,0,0,283,614,1,0,0,0,284,285,5,19,0,
		0,285,286,5,61,0,0,286,287,5,2,0,0,287,288,3,4,2,0,288,291,5,3,0,0,289,
		290,5,19,0,0,290,292,5,125,0,0,291,289,1,0,0,0,291,292,1,0,0,0,292,614,
		1,0,0,0,293,294,5,19,0,0,294,614,5,62,0,0,295,296,5,19,0,0,296,297,5,125,
		0,0,297,306,5,2,0,0,298,303,3,4,2,0,299,300,5,9,0,0,300,302,3,4,2,0,301,
		299,1,0,0,0,302,305,1,0,0,0,303,301,1,0,0,0,303,304,1,0,0,0,304,307,1,
		0,0,0,305,303,1,0,0,0,306,298,1,0,0,0,306,307,1,0,0,0,307,308,1,0,0,0,
		308,311,5,3,0,0,309,310,5,19,0,0,310,312,5,125,0,0,311,309,1,0,0,0,311,
		312,1,0,0,0,312,614,1,0,0,0,313,314,5,19,0,0,314,614,5,125,0,0,315,316,
		5,63,0,0,316,317,5,57,0,0,317,318,5,2,0,0,318,614,5,3,0,0,319,320,5,63,
		0,0,320,321,5,64,0,0,321,322,5,2,0,0,322,614,5,3,0,0,323,324,5,63,0,0,
		324,325,5,65,0,0,325,326,5,2,0,0,326,614,5,3,0,0,327,328,5,63,0,0,328,
		329,5,66,0,0,329,330,5,2,0,0,330,614,5,3,0,0,331,332,5,63,0,0,332,333,
		5,67,0,0,333,334,5,2,0,0,334,614,5,3,0,0,335,336,5,63,0,0,336,337,5,68,
		0,0,337,338,5,2,0,0,338,614,5,3,0,0,339,340,5,63,0,0,340,341,5,69,0,0,
		341,342,5,2,0,0,342,614,5,3,0,0,343,344,5,63,0,0,344,345,5,70,0,0,345,
		346,5,2,0,0,346,349,5,3,0,0,347,348,5,19,0,0,348,350,5,125,0,0,349,347,
		1,0,0,0,349,350,1,0,0,0,350,614,1,0,0,0,351,352,5,63,0,0,352,353,5,71,
		0,0,353,354,5,2,0,0,354,357,5,3,0,0,355,356,5,19,0,0,356,358,5,125,0,0,
		357,355,1,0,0,0,357,358,1,0,0,0,358,614,1,0,0,0,359,360,5,63,0,0,360,361,
		5,72,0,0,361,362,5,2,0,0,362,365,5,3,0,0,363,364,5,19,0,0,364,366,5,125,
		0,0,365,363,1,0,0,0,365,366,1,0,0,0,366,614,1,0,0,0,367,368,5,63,0,0,368,
		369,5,73,0,0,369,370,5,2,0,0,370,614,5,3,0,0,371,372,5,63,0,0,372,373,
		5,74,0,0,373,374,5,2,0,0,374,614,5,3,0,0,375,376,5,63,0,0,376,377,5,75,
		0,0,377,378,5,2,0,0,378,614,5,3,0,0,379,380,5,63,0,0,380,381,5,76,0,0,
		381,382,5,2,0,0,382,614,5,3,0,0,383,384,5,63,0,0,384,385,5,48,0,0,385,
		386,5,2,0,0,386,614,5,3,0,0,387,388,5,63,0,0,388,389,5,49,0,0,389,390,
		5,2,0,0,390,614,5,3,0,0,391,392,5,63,0,0,392,393,5,50,0,0,393,394,5,2,
		0,0,394,614,5,3,0,0,395,396,5,63,0,0,396,397,5,51,0,0,397,398,5,2,0,0,
		398,614,5,3,0,0,399,400,5,63,0,0,400,401,5,77,0,0,401,402,5,2,0,0,402,
		614,5,3,0,0,403,404,5,63,0,0,404,405,5,58,0,0,405,406,5,2,0,0,406,614,
		5,3,0,0,407,408,5,63,0,0,408,409,5,59,0,0,409,410,5,2,0,0,410,614,5,3,
		0,0,411,412,5,63,0,0,412,413,5,78,0,0,413,414,5,2,0,0,414,614,5,3,0,0,
		415,416,5,63,0,0,416,417,5,79,0,0,417,418,5,2,0,0,418,614,5,3,0,0,419,
		420,5,63,0,0,420,421,5,80,0,0,421,422,5,2,0,0,422,614,5,3,0,0,423,424,
		5,63,0,0,424,425,5,81,0,0,425,426,5,2,0,0,426,614,5,3,0,0,427,428,5,63,
		0,0,428,429,5,82,0,0,429,430,5,2,0,0,430,614,5,3,0,0,431,432,5,63,0,0,
		432,433,5,83,0,0,433,434,5,2,0,0,434,614,5,3,0,0,435,436,5,63,0,0,436,
		437,7,5,0,0,437,438,5,2,0,0,438,439,3,4,2,0,439,440,5,3,0,0,440,614,1,
		0,0,0,441,442,5,63,0,0,442,443,5,96,0,0,443,444,5,2,0,0,444,445,3,4,2,
		0,445,446,5,3,0,0,446,614,1,0,0,0,447,448,5,63,0,0,448,449,7,6,0,0,449,
		450,5,2,0,0,450,451,3,4,2,0,451,454,5,3,0,0,452,453,5,19,0,0,453,455,5,
		125,0,0,454,452,1,0,0,0,454,455,1,0,0,0,455,614,1,0,0,0,456,457,5,63,0,
		0,457,458,7,7,0,0,458,459,5,2,0,0,459,460,3,4,2,0,460,461,5,3,0,0,461,
		614,1,0,0,0,462,463,5,63,0,0,463,464,5,97,0,0,464,468,5,2,0,0,465,466,
		3,30,15,0,466,467,5,98,0,0,467,469,1,0,0,0,468,465,1,0,0,0,468,469,1,0,
		0,0,469,470,1,0,0,0,470,471,3,4,2,0,471,472,5,3,0,0,472,614,1,0,0,0,473,
		474,5,63,0,0,474,475,5,99,0,0,475,479,5,2,0,0,476,477,3,30,15,0,477,478,
		5,98,0,0,478,480,1,0,0,0,479,476,1,0,0,0,479,480,1,0,0,0,480,481,1,0,0,
		0,481,482,3,4,2,0,482,483,5,3,0,0,483,614,1,0,0,0,484,485,5,63,0,0,485,
		486,5,100,0,0,486,490,5,2,0,0,487,488,3,30,15,0,488,489,5,98,0,0,489,491,
		1,0,0,0,490,487,1,0,0,0,490,491,1,0,0,0,491,492,1,0,0,0,492,493,3,4,2,
		0,493,494,5,3,0,0,494,614,1,0,0,0,495,496,5,63,0,0,496,497,5,101,0,0,497,
		501,5,2,0,0,498,499,3,32,16,0,499,500,5,98,0,0,500,502,1,0,0,0,501,498,
		1,0,0,0,501,502,1,0,0,0,502,503,1,0,0,0,503,504,3,4,2,0,504,505,5,3,0,
		0,505,614,1,0,0,0,506,507,5,63,0,0,507,508,5,102,0,0,508,512,5,2,0,0,509,
		510,3,32,16,0,510,511,5,98,0,0,511,513,1,0,0,0,512,509,1,0,0,0,512,513,
		1,0,0,0,513,514,1,0,0,0,514,515,3,4,2,0,515,516,5,3,0,0,516,614,1,0,0,
		0,517,518,5,63,0,0,518,519,5,103,0,0,519,523,5,2,0,0,520,521,3,30,15,0,
		521,522,5,98,0,0,522,524,1,0,0,0,523,520,1,0,0,0,523,524,1,0,0,0,524,525,
		1,0,0,0,525,526,3,4,2,0,526,527,5,3,0,0,527,614,1,0,0,0,528,529,5,63,0,
		0,529,530,5,70,0,0,530,534,5,2,0,0,531,532,3,30,15,0,532,533,5,98,0,0,
		533,535,1,0,0,0,534,531,1,0,0,0,534,535,1,0,0,0,535,536,1,0,0,0,536,537,
		3,4,2,0,537,540,5,3,0,0,538,539,5,19,0,0,539,541,5,125,0,0,540,538,1,0,
		0,0,540,541,1,0,0,0,541,614,1,0,0,0,542,543,5,63,0,0,543,544,5,104,0,0,
		544,548,5,2,0,0,545,546,3,30,15,0,546,547,5,98,0,0,547,549,1,0,0,0,548,
		545,1,0,0,0,548,549,1,0,0,0,549,550,1,0,0,0,550,551,3,4,2,0,551,552,5,
		3,0,0,552,614,1,0,0,0,553,554,5,63,0,0,554,555,5,105,0,0,555,559,5,2,0,
		0,556,557,3,30,15,0,557,558,5,98,0,0,558,560,1,0,0,0,559,556,1,0,0,0,559,
		560,1,0,0,0,560,561,1,0,0,0,561,562,3,4,2,0,562,563,5,3,0,0,563,614,1,
		0,0,0,564,565,5,63,0,0,565,566,5,62,0,0,566,570,5,2,0,0,567,568,3,30,15,
		0,568,569,5,98,0,0,569,571,1,0,0,0,570,567,1,0,0,0,570,571,1,0,0,0,571,
		572,1,0,0,0,572,573,3,4,2,0,573,574,5,3,0,0,574,614,1,0,0,0,575,576,5,
		63,0,0,576,577,5,106,0,0,577,578,5,2,0,0,578,579,3,4,2,0,579,580,5,9,0,
		0,580,581,3,4,2,0,581,582,5,3,0,0,582,614,1,0,0,0,583,584,5,63,0,0,584,
		585,5,107,0,0,585,586,5,2,0,0,586,587,3,36,18,0,587,588,5,108,0,0,588,
		589,3,30,15,0,589,590,5,18,0,0,590,591,3,4,2,0,591,592,5,98,0,0,592,593,
		3,4,2,0,593,594,5,3,0,0,594,614,1,0,0,0,595,596,5,63,0,0,596,597,5,125,
		0,0,597,606,5,2,0,0,598,603,3,4,2,0,599,600,5,9,0,0,600,602,3,4,2,0,601,
		599,1,0,0,0,602,605,1,0,0,0,603,601,1,0,0,0,603,604,1,0,0,0,604,607,1,
		0,0,0,605,603,1,0,0,0,606,598,1,0,0,0,606,607,1,0,0,0,607,608,1,0,0,0,
		608,611,5,3,0,0,609,610,5,19,0,0,610,612,5,125,0,0,611,609,1,0,0,0,611,
		612,1,0,0,0,612,614,1,0,0,0,613,215,1,0,0,0,613,219,1,0,0,0,613,223,1,
		0,0,0,613,227,1,0,0,0,613,231,1,0,0,0,613,235,1,0,0,0,613,239,1,0,0,0,
		613,245,1,0,0,0,613,251,1,0,0,0,613,257,1,0,0,0,613,266,1,0,0,0,613,270,
		1,0,0,0,613,274,1,0,0,0,613,278,1,0,0,0,613,284,1,0,0,0,613,293,1,0,0,
		0,613,295,1,0,0,0,613,313,1,0,0,0,613,315,1,0,0,0,613,319,1,0,0,0,613,
		323,1,0,0,0,613,327,1,0,0,0,613,331,1,0,0,0,613,335,1,0,0,0,613,339,1,
		0,0,0,613,343,1,0,0,0,613,351,1,0,0,0,613,359,1,0,0,0,613,367,1,0,0,0,
		613,371,1,0,0,0,613,375,1,0,0,0,613,379,1,0,0,0,613,383,1,0,0,0,613,387,
		1,0,0,0,613,391,1,0,0,0,613,395,1,0,0,0,613,399,1,0,0,0,613,403,1,0,0,
		0,613,407,1,0,0,0,613,411,1,0,0,0,613,415,1,0,0,0,613,419,1,0,0,0,613,
		423,1,0,0,0,613,427,1,0,0,0,613,431,1,0,0,0,613,435,1,0,0,0,613,441,1,
		0,0,0,613,447,1,0,0,0,613,456,1,0,0,0,613,462,1,0,0,0,613,473,1,0,0,0,
		613,484,1,0,0,0,613,495,1,0,0,0,613,506,1,0,0,0,613,517,1,0,0,0,613,528,
		1,0,0,0,613,542,1,0,0,0,613,553,1,0,0,0,613,564,1,0,0,0,613,575,1,0,0,
		0,613,583,1,0,0,0,613,595,1,0,0,0,614,29,1,0,0,0,615,618,5,125,0,0,616,
		617,5,17,0,0,617,619,3,0,0,0,618,616,1,0,0,0,618,619,1,0,0,0,619,31,1,
		0,0,0,620,625,3,30,15,0,621,622,5,9,0,0,622,624,3,30,15,0,623,621,1,0,
		0,0,624,627,1,0,0,0,625,623,1,0,0,0,625,626,1,0,0,0,626,33,1,0,0,0,627,
		625,1,0,0,0,628,630,5,109,0,0,629,631,3,2,1,0,630,629,1,0,0,0,630,631,
		1,0,0,0,631,632,1,0,0,0,632,654,5,110,0,0,633,635,5,111,0,0,634,636,3,
		2,1,0,635,634,1,0,0,0,635,636,1,0,0,0,636,637,1,0,0,0,637,654,5,110,0,
		0,638,640,5,112,0,0,639,641,3,2,1,0,640,639,1,0,0,0,640,641,1,0,0,0,641,
		642,1,0,0,0,642,654,5,110,0,0,643,645,5,113,0,0,644,646,3,2,1,0,645,644,
		1,0,0,0,645,646,1,0,0,0,646,647,1,0,0,0,647,654,5,110,0,0,648,650,5,114,
		0,0,649,651,3,2,1,0,650,649,1,0,0,0,650,651,1,0,0,0,651,652,1,0,0,0,652,
		654,5,110,0,0,653,628,1,0,0,0,653,633,1,0,0,0,653,638,1,0,0,0,653,643,
		1,0,0,0,653,648,1,0,0,0,654,35,1,0,0,0,655,656,5,125,0,0,656,37,1,0,0,
		0,657,658,5,119,0,0,658,39,1,0,0,0,50,80,87,95,111,120,138,146,154,156,
		164,171,178,181,188,196,202,208,213,264,291,303,306,311,349,357,365,454,
		468,479,490,501,512,523,534,540,548,559,570,603,606,611,613,618,625,630,
		635,640,645,650,653
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
